### ISSUE TITLE
Implement backend testing libraries

### ISSUE THREAD

**Issue by edwardhuahan** [uoftblueprint/tces#10]
Same thing as #9 but for the backend

**Comment by kenneth-miura** [comment]
https://jestjs.io/ We are using this for backend testing. 

We don't actually have anything we actually want to test in the backend, so just to be explicit, completion conditions are basically:

1. Installing the library
2. Setting up a test for below endpoint, so checking response value + code. It's not something we actually want to test, but good as sanity check that lib is installed 

![image](https://user-images.githubusercontent.com/22108651/200196663-112101ec-39d1-493a-b89f-9576f0c3ee56.png)

**Comment by kenneth-miura** [comment]
Updated steps: 
1. Installing jest
2. Add a script to tces/package.json called "test" that runs tests in the server.
3. You make a test where you send a fetch request to the /api endpoint, and then verify that you get the expected response of "Hello from server!" , and the expected status code of 200.
