### ISSUE TITLE
Job Listing Card 

### ISSUE THREAD

**Issue by edwardhuahan** [uoftblueprint/tces#20]
As seen on the job page section in figma, we need to have cards that can display all relevant job info for a specific Job Posting (Job Lead)

Send a screenshot in your PR and use dummy JSON data to feed into your card since our backend CRUD is not ready yet!

<img width="352" alt="Screen Shot 2022-11-13 at 10 46 18 AM" src="https://user-images.githubusercontent.com/17802344/201530691-5bc658d6-b296-40e4-91f1-9dcbedf17261.png">

**Comment by kenneth-miura** [comment]
JSON dummy data should be in following format:
```json
{
"id": ObjectId("fe0b3acec32e1fb86cdbe9cd"),
"title": "Lorem",
"pay_per_hour": 72,
"employer_name": "Shopper's Drug Mart",
"email": "shoppers@example.com",
"description": "Lorem",
"type": "Permanent",
"expiry_date": ISODate("2016-04-08T15:06:21.595Z"),
"creation_date": ISODate("2016-04-08T15:06:21.595Z"),
"owner_id": ObjectId("8e83ffe1f1c3638c3fc6653c"),
"creator_id": ObjectId("e18debaeab4ebb39ceea0f3a"),
"timeline":{
    "notes": [
          {
          "text": "Lorem",
          "category": "Lorem"
          },
          {
          "text": "Lorem2",
          "category": "Lorem2"
          }
     ]
} 
,
"employer_id": ObjectId("cabca54558fe16d6cca2af67")
}
```



Source: https://github.com/uoftblueprint/tces/wiki/Database-Schema#job

This would require some joins, if u are wondering why it doesn't look exactly the job collection.
