### ISSUE TITLE
Activity Timeline (Basically Twitter)

### ISSUE THREAD

**Issue by edwardhuahan** [uoftblueprint/tces#21]
On the employer page, there is an activity timeline which functions as a record to indicate to TCES when employees have contacted an employer before. Implement the timeline to show previous posts and also implement a button to create a post. We don't have the backend setup yet so please just use dummy data for the frontend. It's basically twitter.

Don't worry about styling, use [MUI's timeline component](https://mui.com/material-ui/react-timeline/) and just have it function 

<img width="350" alt="Screen Shot 2022-11-13 at 10 49 03 AM" src="https://user-images.githubusercontent.com/17802344/201530812-e12c04d9-3d8d-4919-b7d1-816cd168010d.png">

You can have it look like this for prototyping.

<img width="719" alt="Screen Shot 2022-11-13 at 10 51 59 AM" src="https://user-images.githubusercontent.com/17802344/201530946-dd1a36b5-9c30-4ffe-8b67-dc1ed77145d1.png">

**Comment by kenneth-miura** [comment]
Assume there is a backend endpoint that returns JSON of the following format, for timeline:

```json
{
    "notes": [
          {
          "text": "Lorem",
          "category": "Lorem"
          },
          {
          "text": "Lorem2",
          "category": "Lorem2"
          }
     ]
}
```

[Source](https://github.com/uoftblueprint/tces/wiki/Database-Schema#timeline)
