### ISSUE TITLE
Add a textfield and button that demonstrates communication between frontend and backend

### ISSUE THREAD

**Issue by edwardhuahan** [uoftblueprint/tces#3]
Our app needs a database! Unfortunately as of right now we only have communication between our frontend and backend.
(DB does not exist yet, so a blocker is waiting on ticket #2.)

- Create some type of input that shows you can pass JSON data back and forth between frontend and backend
- Allow this input to communicate between backend and database.
- Add a screenshot if you can

**Comment by jordanjanakievski** [comment]
Still getting a CORS issue when making calls from the frontend. No issues for both POST and GET requests from Postman

**Comment by jordanjanakievski** [comment]
<img width="1512" alt="Screenshot 2022-11-08 at 14 57 52" src="https://user-images.githubusercontent.com/41130718/200670108-b99fa099-e432-400c-9fa4-a4c4d656acde.png">
<img width="1392" alt="Screenshot 2022-11-08 at 14 58 24" src="https://user-images.githubusercontent.com/41130718/200670116-8b0aaeb3-f59e-4642-94c7-15d582e76239.png">
