### ISSUE TITLE
Create a Job Page linked to the backend

### ISSUE THREAD

**Issue by edwardhuahan** [uoftblueprint/tces#43]
We need a frontend interface to connect to the backend that we have, it should look similar to this mockup, this issue is linked to #26 

<img width="689" alt="Screen Shot 2022-11-27 at 3 07 33 PM" src="https://user-images.githubusercontent.com/17802344/204157242-fae41e90-d95d-46d6-b687-5d7e0649a92b.png">

We need to be able to read and update data.

Please reference the [figma](https://www.figma.com/files/team/869392089429802388) designs. This one is only currently available as a lofi design in the Wireframe file.
<img width="846" alt="Screen Shot 2023-01-12 at 7 22 23 PM" src="https://user-images.githubusercontent.com/17802344/212222347-2e7a71e2-3428-442a-9c70-7decf5393b33.png">

The way editing should look isn't entirely fleshed out yet. Do it in some way, expect it to probably be overwritten later.

This is one you need to **verify** with the designers, and also ask them questions as u go

**Comment by helen-li** [comment]
Information card relies on the component built in #20 - need to connect to backend for GET and PUT

**Comment by helen-li** [comment]
Just linked the branch that I was working on, a quick breakdown of the changes I have in there:

* started making a header component for the page in `Header.tsx`
* wrote the async functions for connecting to backend in `Job.tsx` (i haven't tested them with useEffect so no guarantees they work right now, ping me if you are struggling with them)
* all the changes in the `server` dir is unrelated to this ticket lol but please include them - just stuff I had to add bc a new field got added to the Jobs collection schema after my Jobs endpoints PR got merged already
