### ISSUE TITLE
Navigation bar on top!

### ISSUE THREAD

**Issue by edwardhuahan** [uoftblueprint/tces#8]
Most web apps have a navbar on the top, with useful links and user icons. Even github has one! Implement a simple navbar with a dummy logo of your choice and some dummy links. 

<img width="1435" alt="Screen Shot 2022-10-30 at 2 50 52 PM" src="https://user-images.githubusercontent.com/17802344/198896221-0f491bc0-2adc-4c01-b528-57bce58885ef.png">

- Create a navbar using MUI

**Comment by DHRUVKHANDELWAL00** [comment]
hey @edwardhuahan , please assign it to me

**Comment by Manal-jpg** [comment]
<img width="1440" alt="Screen Shot 2022-11-13 at 14 48 09" src="https://user-images.githubusercontent.com/78574063/201541218-f9db6dc0-ba1b-4970-964e-0d40b7f323cc.png">

**Comment by Manal-jpg** [comment]
<img width="325" alt="Screen Shot 2022-11-13 at 14 48 41" src="https://user-images.githubusercontent.com/78574063/201541240-4d6d74ef-1fd1-432f-acac-860aa2a1a88a.png">
